from report_helper import (
    doc, add_heading1, add_heading2, add_heading3,
    add_paragraph, add_bullet, add_code_block, style_table, add_caption
)
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

def build_ch3_ch4_ch5():
    # ==================== CHAPTER 3: SYSTEM DESIGN ====================
    add_heading1("CHAPTER 3\nSYSTEM DESIGN", space_before=16, space_after=16)
    add_heading2("3.1 System Architecture")
    add_paragraph("ExpenseIQ follows a three-tier client-server architecture. The user interacts with the React frontend running in a web browser. The frontend dispatches asynchronous HTTP requests via Axios to the Express.js backend. The backend authenticates requests via JWT middleware, invokes Mongoose models, and reads from or writes to the MongoDB database. The aggregated JSON response returns through the pipeline and renders dynamically on the React interface.")

    if os.path.exists("report_assets/fig3_1_architecture.png"):
        p_img = doc.add_paragraph()
        p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p_img.paragraph_format.space_before = Pt(6)
        p_img.paragraph_format.space_after = Pt(4)
        p_img.add_run().add_picture("report_assets/fig3_1_architecture.png", width=Inches(5.5))
    add_caption("Figure 3.1: System Architecture")

    add_paragraph("The architecture enforces strong separation of concerns across four primary layers:")
    add_bullet("Presentation Layer: ", "React 18, React Router DOM, Chart.js, and custom glassmorphism CSS deliver a responsive single-page experience.")
    add_bullet("Application Layer: ", "Node.js and Express.js expose REST API endpoints, enforce authentication middleware, and validate request payloads.")
    add_bullet("Persistence Layer: ", "MongoDB stores document collections (Users, Categories, Transactions), while Mongoose defines schemas and aggregation pipelines.")
    add_bullet("Communication Layer: ", "RESTful HTTP verbs (GET, POST, PUT, DELETE) and JSON payloads connect the frontend client with the backend server.")

    add_heading2("Data Flow Diagram – Level 0")
    add_paragraph("The Level 0 context data flow diagram represents ExpenseIQ as a centralized process interacting with the user and the MongoDB database.")

    if os.path.exists("report_assets/fig3_2_dfd0.png"):
        p_img = doc.add_paragraph()
        p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p_img.paragraph_format.space_before = Pt(6)
        p_img.paragraph_format.space_after = Pt(4)
        p_img.add_run().add_picture("report_assets/fig3_2_dfd0.png", width=Inches(5.5))
    add_caption("Figure 3.2: Data Flow Diagram - Level 0")

    add_heading2("Data Flow Diagram – Level 1")
    add_paragraph("The Level 1 diagram decomposes the system into four core functional processes: Authentication, Category Management, Transaction Engine, and Analytics Aggregation.")

    if os.path.exists("report_assets/fig3_3_dfd1.png"):
        p_img = doc.add_paragraph()
        p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p_img.paragraph_format.space_before = Pt(6)
        p_img.paragraph_format.space_after = Pt(4)
        p_img.add_run().add_picture("report_assets/fig3_3_dfd1.png", width=Inches(5.5))
    add_caption("Figure 3.3: Data Flow Diagram - Level 1")

    add_heading2("Use Case Diagram")
    add_paragraph("The use case diagram illustrates the primary user interactions supported by the ExpenseIQ system.")

    if os.path.exists("report_assets/fig3_4_usecase.png"):
        p_img = doc.add_paragraph()
        p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p_img.paragraph_format.space_before = Pt(6)
        p_img.paragraph_format.space_after = Pt(4)
        p_img.add_run().add_picture("report_assets/fig3_4_usecase.png", width=Inches(5.0))
    add_caption("Figure 3.4: Use Case Diagram")

    doc.add_page_break()

    add_heading2("3.2 Database Design")
    add_paragraph("The application utilizes MongoDB collections for three main resources: Users, Categories, and Transactions. Schemas are structured with Mongoose to ensure strict type checking and reference integrity.")

    add_heading3("Table 3.1: Users Collection Schema")
    tbl_u = doc.add_table(rows=1, cols=3)
    u_headers = ["Field", "Type", "Description"]
    u_widths = [Inches(1.5), Inches(1.5), Inches(3.3)]
    u_data = [
        ["_id", "ObjectId", "Unique user identifier generated by MongoDB."],
        ["name", "String", "Full name of the registered user."],
        ["email", "String", "Unique email address used for authentication."],
        ["password", "String", "Bcrypt-hashed password (excluded from default queries)."],
        ["createdAt", "Date", "Timestamp of account registration."]
    ]
    style_table(tbl_u, u_widths, u_headers, u_data)
    add_caption("Table 3.1: Users Collection Schema")

    add_heading3("Table 3.2: Categories Collection Schema")
    tbl_c = doc.add_table(rows=1, cols=3)
    c_headers = ["Field", "Type", "Description"]
    c_widths = [Inches(1.5), Inches(1.5), Inches(3.3)]
    c_data = [
        ["_id", "ObjectId", "Unique category identifier."],
        ["name", "String", "Name of the category (e.g., Salary, Food & Dining)."],
        ["type", "String", "Classification: income or expense."],
        ["color", "String", "Hexadecimal color code for charts and badges."],
        ["icon", "String", "Emoji or icon symbol representing the category."],
        ["user", "ObjectId", "Reference to the owning User document."]
    ]
    style_table(tbl_c, c_widths, c_headers, c_data)
    add_caption("Table 3.2: Categories Collection Schema")

    add_heading3("Table 3.3: Transactions Collection Schema")
    tbl_t = doc.add_table(rows=1, cols=3)
    t_headers = ["Field", "Type", "Description"]
    t_widths = [Inches(1.5), Inches(1.5), Inches(3.3)]
    t_data = [
        ["_id", "ObjectId", "Unique transaction identifier."],
        ["type", "String", "Transaction type: income or expense."],
        ["amount", "Number", "Monetary transaction value (positive float)."],
        ["category", "ObjectId", "Reference to the associated Category document."],
        ["description", "String", "Optional descriptive note for the transaction."],
        ["date", "Date", "Date and time when the transaction occurred."],
        ["user", "ObjectId", "Reference to the owning User document."]
    ]
    style_table(tbl_t, t_widths, t_headers, t_data)
    add_caption("Table 3.3: Transactions Collection Schema")

    doc.add_page_break()

    # ==================== CHAPTER 4: TECHNOLOGY STACK ====================
    add_heading1("CHAPTER 4\nTECHNOLOGY STACK", space_before=16, space_after=16)
    add_heading2("4.1 MongoDB")
    add_paragraph("MongoDB is a high-performance NoSQL document-oriented database that stores records in flexible BSON (Binary JSON) documents. In ExpenseIQ, MongoDB persists user credentials, custom categories, and all transaction histories. Its document model aligns seamlessly with JavaScript objects utilized in Node.js, providing rapid querying, indexing, and aggregation pipelines without complex SQL joins.")

    add_heading2("4.2 Express.js")
    add_paragraph("Express.js is a minimalist web application framework for Node.js used to architect the backend REST API of ExpenseIQ. Express handles URL routing, parses JSON request bodies, verifies JWT bearer tokens through custom middleware, and manages cross-origin resource requests (CORS). It provides structured controllers for authentication, transactions, and report generation.")

    add_heading2("4.3 React.js")
    add_paragraph("React.js is an industry-standard JavaScript library for building responsive user interfaces through modular, component-driven architecture. ExpenseIQ leverages React 18, utilizing React Hooks such as useState, useEffect, and useContext for centralized authentication state and reactive data fetching. It renders dynamic summary cards, interactive charts, filterable tables, and modal dialogues.")

    add_heading2("4.4 Node.js")
    add_paragraph("Node.js is an open-source, cross-platform JavaScript runtime environment powered by Google’s V8 engine. It allows JavaScript execution on the server side. In ExpenseIQ, Node.js drives the backend server, processing asynchronous database calls non-blockingly and ensuring high concurrency and quick response times.")

    add_heading2("4.5 Other Tools / Libraries")
    add_bullet("Chart.js & react-chartjs-2: ", "Flexible charting library used to render interactive line charts (12-month income vs expense trends) and doughnut charts (category spending distribution).")
    add_bullet("Mongoose ODM: ", "Object Data Modeling library providing schema enforcement, validation, model hooks (pre-save password hashing), and aggregation pipelines.")
    add_bullet("JSON Web Tokens (JWT) & bcryptjs: ", "Secure user authentication mechanism implementing salted password hashing and stateless token verification.")
    add_bullet("Vite: ", "Next-generation frontend build tool providing instantaneous Hot Module Replacement (HMR) and optimized production bundling.")
    add_bullet("React Router DOM: ", "Client-side routing library enabling protected routes, page transitions, and seamless navigation between Dashboard, Transactions, Categories, and Reports.")
    add_bullet("Custom CSS Design System: ", "Modern dark glassmorphism stylesheet utilizing backdrop filters, glowing accents, Inter typography, and responsive layout grids.")

    add_heading2("MERN Architecture Summary")
    add_paragraph("The MERN stack provides a unified JavaScript-based ecosystem across the entire application lifecycle. React delivers an engaging single-page user interface; Node.js and Express.js handle API requests and business logic; and MongoDB reliably persists data. This full-stack JavaScript architecture minimizes context switching, promotes code reuse, and represents an ideal framework for building scalable web applications.")

    doc.add_page_break()

    # ==================== CHAPTER 5: SYSTEM IMPLEMENTATION ====================
    add_heading1("CHAPTER 5\nSYSTEM IMPLEMENTATION", space_before=16, space_after=16)
    add_heading2("5.1 Module 1 – Authentication & User Management")
    add_paragraph("The Authentication module manages user registration, login, and session validation. When a new user registers with their name, email, and password, the system hashes the password using bcryptjs and automatically seeds twelve standard default categories (Salary, Freelance, Food, Transportation, Shopping, Utilities, Entertainment, Healthcare, etc.). Upon successful login, a JWT token is generated and persisted in localStorage.")

    add_heading2("5.2 Module 2 – Category & Transaction Management")
    add_paragraph("The Category Management module allows users to create custom income and expense categories, assigning custom icons and hex colors. The Transaction Tracking module provides a controlled modal form to record transaction amounts, categories, dates, and descriptions. Users can filter transactions by type, month, and year with real-time UI updates and pagination.")

    add_heading2("5.3 API / Backend Implementation - code")
    add_paragraph("The backend server establishes middleware, routes, and database connections. The core server initialization is shown below:")

    add_code_block("""const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
require('dotenv').config();

const app = express();
app.use(cors());
app.use(express.json());

app.use('/api/auth', require('./routes/auth'));
app.use('/api/categories', require('./routes/categories'));
app.use('/api/transactions', require('./routes/transactions'));
app.use('/api/reports', require('./routes/reports'));

const PORT = process.env.PORT || 5000;
mongoose.connect(process.env.MONGO_URI)
  .then(() => app.listen(PORT, () => console.log(`Server running on port ${PORT}`)))
  .catch(err => console.error('MongoDB connection error:', err));""")

    add_paragraph("The complete REST API specification is detailed in Table 5.1.")

    tbl_api = doc.add_table(rows=1, cols=4)
    api_headers = ["Resource", "Method", "Endpoint", "Description"]
    api_widths = [Inches(1.3), Inches(0.9), Inches(2.2), Inches(2.1)]
    api_data = [
        ["Auth", "POST", "/api/auth/register", "Register new user & seed default categories."],
        ["Auth", "POST", "/api/auth/login", "Authenticate credentials and return JWT token."],
        ["Auth", "GET", "/api/auth/me", "Fetch current authenticated user profile."],
        ["Categories", "GET", "/api/categories", "Get all categories for authenticated user."],
        ["Categories", "POST", "/api/categories", "Create new custom category."],
        ["Categories", "PUT", "/api/categories/:id", "Update category details (name, color, icon)."],
        ["Categories", "DELETE", "/api/categories/:id", "Delete category and cascade remove transactions."],
        ["Transactions", "GET", "/api/transactions", "Query transactions (filters: type, month, year, page)."],
        ["Transactions", "POST", "/api/transactions", "Create new income or expense transaction."],
        ["Transactions", "PUT", "/api/transactions/:id", "Update existing transaction details."],
        ["Transactions", "DELETE", "/api/transactions/:id", "Delete transaction by ID."],
        ["Reports", "GET", "/api/reports/monthly", "12-month aggregated income, expense, and balance."],
        ["Reports", "GET", "/api/reports/by-category", "Category-wise expense breakdown and percentages."]
    ]
    style_table(tbl_api, api_widths, api_headers, api_data)
    add_caption("Table 5.1: REST API Endpoints")

    add_heading3("5.3.1 Mongoose Schema Example")
    add_paragraph("The Mongoose Transaction schema defines field types, validation constraints, and indexing for optimized retrieval:")

    add_code_block("""const mongoose = require('mongoose');

const transactionSchema = new mongoose.Schema({
  type: { type: String, enum: ['income', 'expense'], required: true },
  amount: { type: Number, required: true, min: 0.01 },
  category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', required: true },
  description: { type: String, trim: true, default: '' },
  date: { type: Date, default: Date.now, required: true },
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }
}, { timestamps: true });

transactionSchema.index({ user: 1, date: -1 });
module.exports = mongoose.model('Transaction', transactionSchema);""")

    add_heading3("5.3.2 Monthly Aggregation Pipeline")
    add_paragraph("The reports endpoint uses MongoDB aggregation pipelines to calculate monthly totals for income and expense:")

    add_code_block("""const result = await Transaction.aggregate([
  {
    $match: {
      user: new mongoose.Types.ObjectId(req.user._id),
      date: { $gte: startDate, $lte: endDate }
    }
  },
  {
    $group: {
      _id: { month: { $month: '$date' }, type: '$type' },
      total: { $sum: '$amount' },
      count: { $sum: 1 }
    }
  },
  { $sort: { '_id.month': 1 } }
]);""")

    add_heading2("5.4 Frontend Implementation - code")
    add_paragraph("The React frontend organizes state using React Hooks and communicates via an Axios interceptor:")

    add_code_block("""// Axios JWT interceptor setup
import axios from 'axios';
const api = axios.create({ baseURL: 'http://localhost:5000/api' });

api.interceptors.request.use((config) => {
  const token = localStorage.getItem('token');
  if (token) config.headers.Authorization = `Bearer ${token}`;
  return config;
});

// React Transaction State Management
const [transactions, setTransactions] = useState([]);
const [filterType, setFilterType] = useState('');
const [filterMonth, setFilterMonth] = useState('');

const loadTransactions = async (page = 1) => {
  const res = await api.get(`/transactions?page=${page}&type=${filterType}&month=${filterMonth}`);
  setTransactions(res.data.transactions);
};""")

    doc.add_page_break()